# Lab | Pandas Deep-Dive

### 1. Import Pandas package under the alias pd and Numpy under the alias np

In [1]:
import pandas as pd
import numpy as np
import os

### 2. Define a variable called `path` that contains the path to the csv file you downloaded. 

In [5]:
print(os.listdir('..'))
print(os.path.join('data', 'README.md', 'your-code'))
path = os.path.join("..", "data") #utiliser paht pour rechercher un fichier demandé via le ficher parent  
path

['README.md', 'your-code']
data\README.md\your-code


'..\\data'

### 3. Using the Pandas `read_csv()` method, import the csv file at the path above. 

Assign the returned value to a variable called `data`.

Note: you can omit the `sep` parameter for `read_csv()` because the csv file uses the default separator of ",".

In [10]:
ls

 Le volume dans le lecteur C s’appelle OS
 Le numéro de série du volume est 1498-E450

 Répertoire de C:\Users\Stressis\Documents\GitHub\ironhack-datalabs-dataparis0619-pt\module-2\lab-pandas-deep-dive\your-code

27/08/2019  21:10    <DIR>          .
27/08/2019  21:10    <DIR>          ..
03/06/2019  20:47                 0 .gitkeep
27/08/2019  20:50    <DIR>          .ipynb_checkpoints
03/06/2019  20:47           551 086 apple_store.csv
03/06/2019  20:47    <DIR>          data
27/08/2019  21:10            15 982 main.ipynb
               3 fichier(s)          567 068 octets
               4 Rép(s)  55 635 562 496 octets libres


In [14]:
#file_list = [f for f in os.listdir("../data") if f.endswith('.csv')]
#data_sets = [pd.read_csv(os.path.join('../data', f)) for f in file_list]
#data = pd.concat(data_sets, axis=0)

""" voir avec Y pour path qui ne focntionne pas copie du fichier pour le recuperer directement """

data = pd.read_csv('apple_store.csv')


### 4. Print the first 5 rows of `data` to see what the data look like.

A data analyst usually does this to have a general understanding about what the data look like before digging deep.

In [15]:
data.head(5)



id                                         track_name  size_bytes  \
0  281656475                                    PAC-MAN Premium   100788224   
1  281796108                          Evernote - stay organized   158578688   
2  281940292    WeatherBug - Local Weather, Radar, Maps, Alerts   100524032   
3  282614216  eBay: Best App to Buy, Sell, Save! Online Shop...   128512000   
4  282935706                                              Bible    92774400   

   price  rating_count_tot  rating_count_ver  user_rating  user_rating_ver  \
0   3.99             21292                26          4.0              4.5   
1   0.00            161065                26          4.0              3.5   
2   0.00            188583              2822          3.5              4.5   
3   0.00            262241               649          4.0              4.5   
4   0.00            985920              5320          4.5              5.0   

    prime_genre  
0         Games  
1  Productivity  
2       Weather  
3      Shopping  
4     Reference

### 5. Print the summary (info) of the data.

In [16]:
data.describe()

id    size_bytes        price  rating_count_tot  \
count  7.197000e+03  7.197000e+03  7197.000000      7.197000e+03   
mean   8.631310e+08  1.991345e+08     1.726218      1.289291e+04   
std    2.712368e+08  3.592069e+08     5.833006      7.573941e+04   
min    2.816565e+08  5.898240e+05     0.000000      0.000000e+00   
25%    6.000937e+08  4.692275e+07     0.000000      2.800000e+01   
50%    9.781482e+08  9.715302e+07     0.000000      3.000000e+02   
75%    1.082310e+09  1.819249e+08     1.990000      2.793000e+03   
max    1.188376e+09  4.025970e+09   299.990000      2.974676e+06   

       rating_count_ver  user_rating  user_rating_ver  
count       7197.000000  7197.000000      7197.000000  
mean         460.373906     3.526956         3.253578  
std         3920.455183     1.517948         1.809363  
min            0.000000     0.000000         0.000000  
25%            1.000000     3.500000         2.500000  
50%           23.000000     4.000000         4.000000  
75%          140.000000     4.500000         4.500000  
max       177050.000000     5.000000         5.000000

### 6. Print the number of columns in the data.

In [17]:
len(data.columns)

9

### 7. Print all column names.

In [18]:
list(data)

['id',
 'track_name',
 'size_bytes',
 'price',
 'rating_count_tot',
 'rating_count_ver',
 'user_rating',
 'user_rating_ver',
 'prime_genre']

## Now that we have a general understanding of the data, we'll start working on the challenge questions.

### 8. How many apps are there in the data source? 

Print the # of observations of the data.

*Hint: Your code should return the number 7197.*

In [19]:
data.count()

id                  7197
track_name          7197
size_bytes          7197
price               7197
rating_count_tot    7197
rating_count_ver    7197
user_rating         7197
user_rating_ver     7197
prime_genre         7197
dtype: int64

### 9. What is the average rating of all apps? 

First, read the `user_rating` column into a varialbe named `user_rating`.

In [20]:
data['user_rating'].mean()

3.526955675976101

Now you can calculate the average of the `user_rating` data.

Your code should return 3.526955675976101

### 10. How many apps have an average rating no less than 4?

First, filter `user_rating` where its value >= 4. 

Assign the filtered dataframe to a new variable called `user_rating_high`.

In [26]:
user_rating_high = data.loc[(data['user_rating'] >= 4)]

4781

Now obtain the length of `user_rating_high` which should return 4781.

In [27]:
len(user_rating_high)

4781

### 11. How many genres are there in total for all the apps?

Define a new variable named `genres` that contains the `prime_genre` column of `data`. Google for how to obtain unique values of a dataframe column. 

In [28]:
genres = data.drop_duplicates('prime_genre')


Print the length of the unique values of `genres`. Your code should return 23.

In [30]:
len(genres)

23

### 12. What are the top 3 genres that have the most number of apps?

What you want to do is to count the number of occurrences of each unique genre values. Because you already know how to obtain the unique genre values, you can of course count the # of apps of each genre one by one. However, Pandas has a convient function to let you count all values of a dataframe column with a single command. Google for "pandas count values" to find the solution. Your code should return the following:

```
Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64
```

In [35]:
data['prime_genre'].value_counts()

Games                3862
Entertainment         535
Education             453
Photo & Video         349
Utilities             248
Health & Fitness      180
Productivity          178
Social Networking     167
Lifestyle             144
Music                 138
Shopping              122
Sports                114
Book                  112
Finance               104
Travel                 81
News                   75
Weather                72
Reference              64
Food & Drink           63
Business               57
Navigation             46
Medical                23
Catalogs               10
Name: prime_genre, dtype: int64

### 13. Which genre is most likely to contain free apps?

First, filter `data` where the price is 0.00. Assign the filtered data to a new variable called `free_apps`. Then count the values in `free_apps`. Your code should return:

```
Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Shopping              121
Utilities             109
Lifestyle              94
Finance                84
Sports                 79
Health & Fitness       76
Music                  67
Book                   66
Productivity           62
News                   58
Travel                 56
Food & Drink           43
Weather                31
Navigation             20
Reference              20
Business               20
Catalogs                9
Medical                 8
Name: prime_genre, dtype: int64
```

In [41]:
free_apps = data.loc[(data['price'] <= 0.00)]
free_apps

id                                         track_name  \
1      281796108                          Evernote - stay organized   
2      281940292    WeatherBug - Local Weather, Radar, Maps, Alerts   
3      282614216  eBay: Best App to Buy, Sell, Save! Online Shop...   
4      282935706                                              Bible   
6      283646709             PayPal - Send and request money safely   
7      284035177                            Pandora - Music & Radio   
12     284815942               Google – Search made just for mobile   
13     284847138                   Bank of America - Mobile Banking   
15     284876795             TripAdvisor Hotels Flights Restaurants   
16     284882215                                           Facebook   
17     284910350     Yelp - Nearby Restaurants, Shopping & Services   
18     284993459  Shazam - Discover music, artists, videos & lyrics   
22     286058814    Yahoo Sports - Teams, Scores, News & Highlights   
25     286906691          Lifesum – Inspiring healthy lifestyle app   
26     286911400                                           Hangman.   
27     288113403      iTranslate - Language Translator & Dictionary   
30     288429040                                           LinkedIn   
33     289523017                          Blackjack by MobilityWare   
35     290638154          iHeartRadio – Free Music & Radio Stations   
41     292738169  Deezer - Listen to your Favorite Music & Playl...   
43     293523031                                   Sonos Controller   
45     293622097                                       Google Earth   
47     293778748                                            PAC-MAN   
48     294056623                                  FOX Sports Mobile   
53     295646461      The Weather Channel: Forecast, Radar & Alerts   
56     296581815                OpenTable - Restaurant Reservations   
59     297368629  Lose It! – Weight Loss Program and Calorie Cou...   
60     297430070                                             Target   
62     297606951  Amazon App: shop, scan, compare, and read reviews   
66     298596830                                          NRJ Radio   
...          ...                                                ...   
7147  1180340451                     Valley of Fear Virtual Reality   
7148  1180467988   Christmas Swap 3 -Match toy & candy to countdown   
7149  1180478894                                       不良西游-神魔悟空大战篇   
7150  1180885427  VR Horror Maze Walk :Horror Fever For VR Cardb...   
7151  1180914367                                          食べないと死ぬ 3   
7153  1180939298                         クリスマスミッケ/脱出ゲーム感覚の絵探しパズルゲーム   
7157  1181283568                                               机で卓球   
7158  1181358720              VPN Go - Safe Fast & Stable VPN Proxy   
7161  1181601206                                    Truth or Dare ·   
7163  1181633163                           NORAD Tracks Santa Claus   
7166  1181904201   4x4 Dirt Track Trials Forest Driving Parking Sim   
7167  1182265441                      脱出ゲーム　わたしをみつけて　-おじいさんとわたしの物語-   
7168  1182331762                      Escape from the frigid Igloo.   
7170  1183234072                                          CTFxCmoji   
7171  1183260922                    Room Escape Game - Santa's Room   
7174  1183856228  VR Thrills: Roller Coaster 360 (Google Cardboard)   
7175  1183986102   Santa Kids Hair Salon - Christmas Makeover Games   
7176  1184711626                                 Human Juggling Cup   
7177  1184800011                           Again - room escape game   
7179  1185328193             Fam — Group video calling for iMessage   
7180  1185365336                   Laurie Hernandez the Human Emoji   
7182  1185538497                                  camera for filter   
7184  1185731859                                    剑客情缘-高爆率高掉落天天疯玩   
7186  1186108496                 脱出ゲーム - 書道教室 -  "漢字"の謎に満ちた部屋からの 脱出   
7187  1186126548                      

### 14. Now you can calculate the proportion of the free apps in each genre based on the value counts you obtained in the previous two steps. 

Challenge yourself by achieving that with one line of code. The output should look like:

```
Shopping             0.991803
Catalogs             0.900000
Social Networking    0.856287
Finance              0.807692
News                 0.773333
Sports               0.692982
Travel               0.691358
Food & Drink         0.682540
Lifestyle            0.652778
Entertainment        0.624299
Book                 0.589286
Games                0.584412
Music                0.485507
Photo & Video        0.478510
Utilities            0.439516
Navigation           0.434783
Weather              0.430556
Health & Fitness     0.422222
Business             0.350877
Productivity         0.348315
Medical              0.347826
Reference            0.312500
Education            0.291391
Name: prime_genre, dtype: float64
```

The numbers are interesting, aren't they?

In [ ]:
"""value_counts/len"""



### 15. If a developer tries to make money by developing and selling Apple Store apps, in which genre should s/he develop the apps? Please assume all apps cost the same amount of time and expense to develop.

We will leave this question to you. There are several way to solve it. Ideally your output should look like below:

```
    average_price              genre
21       8.776087            Medical
11       5.116316           Business
4        4.836875          Reference
6        4.835435              Music
1        4.330562       Productivity
15       4.124783         Navigation
16       4.028234          Education
12       1.916444   Health & Fitness
20       1.790536               Book
7        1.647621          Utilities
2        1.605417            Weather
18       1.552381       Food & Drink
14       1.473295      Photo & Video
0        1.432923              Games
8        1.120370             Travel
10       0.953070             Sports
13       0.889701      Entertainment
17       0.885417          Lifestyle
22       0.799000           Catalogs
19       0.517733               News
5        0.421154            Finance
9        0.339880  Social Networking
3        0.016311           Shopping
```